In [1]:
import tensorflow as tf 
import numpy as np

In [2]:
tensor_1d = np.array([1.3, 1, 4.0, 23.99])

In [3]:
print(tensor_1d)

[  1.3    1.     4.    23.99]


In [4]:
#converting numpy array into a tensor
tf_tensor=tf.convert_to_tensor(tensor_1d,dtype=tf.float64)

In [5]:
with tf.Session() as sess: 
    print(sess.run(tf_tensor))
    print(sess.run(tf_tensor[0]))
    print(sess.run(tf_tensor[2]))

[  1.3    1.     4.    23.99]
1.3
4.0


In [6]:
matrix1 = np.array([(2,2,2),(2,2,2),(2,2,2)],dtype='int32') 
matrix2 = np.array([(1,1,1),(1,1,1),(1,1,1)],dtype='int32')

In [7]:
print("matrix1  =")
print(matrix1)
 
print("matrix2 =" )
print(matrix2)


matrix1  =
[[2 2 2]
 [2 2 2]
 [2 2 2]]
matrix2 =
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [8]:
matrix1 = tf.constant(matrix1) 
matrix2 = tf.constant(matrix2)

In [9]:
matrix_product = tf.matmul(matrix1, matrix2) 
matrix_sum = tf.add(matrix1,matrix2) 

In [10]:
matrix_3 = np.array([(2,7,2),(1,4,2),(9,0,2)],dtype='float32') 
 
print("matrix3 =")
print (matrix_3 )
 
matrix_det = tf.matrix_determinant(matrix_3)

matrix3 =
[[ 2.  7.  2.]
 [ 1.  4.  2.]
 [ 9.  0.  2.]]


In [11]:
with tf.Session() as sess: 
        result1 = sess.run(matrix_product) 
        result2 = sess.run(matrix_sum) 
        result3 = sess.run(matrix_det) 

In [12]:
print "matrix1*matrix2 =" 
print result1 
 
print "matrix1 + matrix2 =" 
print result2 
 
print "matrix3 determinant result =" 
print result3

matrix1*matrix2 =
[[6 6 6]
 [6 6 6]
 [6 6 6]]
matrix1 + matrix2 =
[[3 3 3]
 [3 3 3]
 [3 3 3]]
matrix3 determinant result =
56.0


In [19]:
tensor_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) 
print(tensor_3d )

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Working with an image

In [20]:
import matplotlib.image as mp_image 
filename = "IMG_0024.jpg" 
input_image = mp_image.imread(filename)

In [21]:
print('input dim = {}'.format(input_image.ndim) )
print('input shape = {}'.format(input_image.shape)) 

input dim = 3
input shape = (1280, 1057, 3)


In [ ]:
import matplotlib.pyplot as plt 
plt.imshow(input_image) 
plt.show()                 

In [ ]:
my_image = tf.placeholder("uint8",[None,None,3])

In [ ]:
slice = tf.slice(my_image,[10,0,0],[1000,100,-1])

In [ ]:
with tf.Session() as session: 
    result = session.run(slice,feed_dict={my_image: input_image}) 
    print(result.shape) 
 
plt.imshow(result) 
plt.show()

## Prepare the data for Mandelbrot set

In [12]:
Y, X = np.mgrid[-1.3:1.3:0.005, -2:1:0.005] 
Z = X+1j*Y 
c = tf.constant(Z.astype(np.complex64)) 

In [13]:
zs = tf.Variable(c)

In [14]:
ns = tf.Variable(tf.zeros_like(c, tf.float32)) 

In [15]:
sess = tf.InteractiveSession()

In [16]:
tf.initialize_all_variables().run()

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [17]:
zs_ = zs*zs + c
not_diverged = tf.complex_abs(zs_) < 4
step = tf.group(zs.assign(zs_),ns.assign_add(tf.cast(not_diverged, tf.float32)))
for i in range(200): step.run()

In [18]:
plt.imshow(ns.eval()) 
plt.show() 

NameError: name 'plt' is not defined